# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e3776c27d21de542fa87cbc8af0e4aff1a1e6054c19854439e11df582cef8fdc11e0b3cb85dbbbef9046edfba7a48df0c9a94d2c73f4c9ab732b79e68ee4c39

test:
  secret_key_base: 83bb6a7f4d0eb06e56c13059a25c3ccc1341d5f5e64579cf23e99438329f9798b746938163ba7f31e54df1bc5c9804d98de62f41d22224abf4df47928ddf5c72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
